## NumPy

Open in Colab [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/febse/opt2025-de/blob/main/01-Python/02-Numpy.ipynb)

In der vorherigen Lektion haben wir uns mit Listen beschäftigt. Diese sind sehr flexibel, aber auch sehr langsam. Mit kleinen Listen werden wir das nicht merken, aber wenn wir mit großen Datenmengen arbeiten, dann können lange Laufzeiten zum Problem werden. 

NumPy (Numerical Python) ist ein Paket, das viele Funktionen enthält, die für die Arbeit mit großen Datenmengen geeignet sind.

## Numpy Array

Die grundlegendste Datenstruktur in NumPy ist das Array. Ein Array ist eine Sammlung von Elementen, die alle denselben Datentyp (Zahlen, Zeichenketten, Boolean, etc) haben. 

In [1]:
import numpy as np

x = np.array([2, 7, 5, 2])
print(x)

y = np.ones(4)
print(y)

[2 7 5 2]
[1. 1. 1. 1.]


NumPy-Arrays sind sehr ähnlich zu Listen, aber sie haben einige zusätzliche Eigenschaften.

Sehr nützlich sind die so genannten _vektorisierten_ Operationen. Zum Beispiel möchten wir die Zahl ein s zu jedem Element von `x` addieren. Wir brauchen nur `x + 1` schreiben.  

In [2]:
z = x + 1
z

array([3, 8, 6, 3])

Viele anderen Operationen funktionieren ähnlich. Zum Beispiel `x * 2` multipliziert jedes Element von `x` mit 2. 

In [3]:
x * 2

array([ 4, 14, 10,  4])

`x ** 2` quadriert jedes Element von `x`.

In [4]:
x ** 2

array([ 4, 49, 25,  4])

Addition, Subtraktion, Multiplikation und Division von zwei Arrays funktionieren auch elementweise. Zum Beispiel `x + y` addiert die Elemente von `x` und `y` zusammen.

In [5]:
print(x)
print(y)
x + y

[2 7 5 2]
[1. 1. 1. 1.]


array([3., 8., 6., 3.])

Dasselbe funktioniert mit Python-Listen nicht. Wenn wir zwei Listen addieren, dann werden die Elemente an der gleichen Stelle nicht addiert, sondern die Listen werden aneinander gehängt.

In [6]:
x_list = [2, 7, 5, 2]
y_list = [1, 1, 1, 1]
x_plus_y_list = x_list + y_list
x_plus_y_list

[2, 7, 5, 2, 1, 1, 1, 1]

In [7]:
# x_list + 1

NumPy-Arrays haben auch einige Methoden, die wir mit Listen nicht haben. Zum Beispiel können wir die Summe aller Elemente eines Arrays berechnen.

In [8]:
# Summe der Elemente
print(x.sum())

16


In [9]:
# Durchschnitt der Elemente (Arithmetischer Mittelwert)

x.mean()

np.float64(4.0)

In [10]:
# Standardabweichung
x.std()

np.float64(2.1213203435596424)

In [11]:
# Minimum
x.min()

np.int64(2)

In [12]:
# Maximum
x.max()

np.int64(7)

In [13]:
# Logische Operationen
print(x)
print(x > 3)
print(x == 3)
print(x != 3)
print(x <= 3)


[2 7 5 2]
[False  True  True False]
[False False False False]
[ True  True  True  True]
[ True False False  True]


## Aufgabe 1

Estellen Sie zwei NumPy-Arrays `x1` und `x2` mit den Elementen [3, 1, 11, 3, 5] und [2.2, 34, 11, 5]. Geben Sie die Arrays mit `print` aus.
- Testen Sie, ob die Elemente des ersten Arrays genau gleich 3 sind, speichern Sie das Ergebnis in einer Variablen. Drucken Sie diese Variable mit `print` aus.
- Berechnen Sie die Differenz zwischen dem Maximum und dem Minimum des Arrays. Geben Sie das Ergebnis aus.
- Berechnen Sie den Mittelwert des Arrays. Geben Sie das Ergebnis aus.
- Bestimmen Sie, welche Elemente des zweiten Arrays größer als die des ersten Arrays sind. Geben Sie das Ergebnis aus.

### Slicing

Wir können auch auf die Elemente eines Arrays zugreifen, indem wir einen Index angeben. Der Index beginnt bei 0.

In [15]:
z = np.array(["a", "b", "c", "d", "e"])

In [16]:
# Das erste Element
print(z[0])

a


In [17]:
# Alle Elemente bis zur Indexposition 2 (exklusive)
# Achten Sie darauf, dass der Index 0-basiert ist und daher das dritte Element ist eine Indexposition 2 hat
z[:2]

array(['a', 'b'], dtype='<U1')

In [18]:
print(z[-3])

c


In [19]:
print(z[-3:])

['c' 'd' 'e']


In [20]:
z[1:3]

array(['b', 'c'], dtype='<U1')

## Aufgabe 2

- Erstellen Sie ein NumPy-Array mit den Elementen 2.2, 3.1, 8.2, 9. Geben Sie das Array aus.
- Ersetzen Sie die ersten beiden Elemente des Arrays durch die Werte 1.1 und 2.2. Geben Sie das Array aus.
- Testen Die, ob das letzte Element des Arrays größer als 10 ist. Speichern Sie das Ergebnis in einer Variablen. Geben Sie das Ergebnis aus.
